//! Allow-list of legal held items for Pokémon Champions Regulation M-A.
//!
//! Source: <https://metavgc.com/guides/pokemon-champions-format-legal-pokemon-items-moves>
//! (snapshot extracted from the Next.js flight payload, 117 entries).
//!
//! Includes 64 Mega Stones plus the standard berries / utility items the
//! format ships with. Comparisons go through [`super::common::canonical`],
//! which makes spacing / case insensitive (`Choice Scarf`, `choice-scarf`,
//! `CHOICESCARF` all collide).

pub const ALLOWED_ITEMS_MA: &[&str] = &[
    "Abomasite",
    "Absolite",
    "Aerodactylite",
    "Aggronite",
    "Alakazite",
    "Altarianite",
    "Ampharosite",
    "Aspear Berry",
    "Audinite",
    "Babiri Berry",
    "Banettite",
    "Beedrillite",
    "Black Belt",
    "Black Glasses",
    "Blastoisinite",
    "BrightPowder",
    "Cameruptite",
    "Chandelurite",
    "Charcoal",
    "Charizardite X",
    "Charizardite Y",
    "Charti Berry",
    "Cheri Berry",
    "Chesnaughtite",
    "Chesto Berry",
    "Chilan Berry",
    "Chimechite",
    "Choice Scarf",
    "Chople Berry",
    "Clefablite",
    "Coba Berry",
    "Colbur Berry",
    "Crabominite",
    "Delphoxite",
    "Dragon Fang",
    "Dragoninite",
    "Drampanite",
    "Emboarite",
    "Excadrite",
    "Fairy Feather",
    "Feraligite",
    "Floettite",
    "Focus Band",
    "Focus Sash",
    "Froslassite",
    "Galladite",
    "Garchompite",
    "Gardevoirite",
    "Gengarite",
    "Glalitite",
    "Glimmoranite",
    "Golurkite",
    "Greninjite",
    "Gyaradosite",
    "Haban Berry",
    "Hard Stone",
    "Hawluchanite",
    "Heracronite",
    "Houndoominite",
    "Kangaskhanite",
    "Kasib Berry",
    "Kebia Berry",
    "King's Rock",
    "Leftovers",
    "Leppa Berry",
    "Light Ball",
    "Lopunnite",
    "Lucarionite",
    "Lum Berry",
    "Magnet",
    "Manectite",
    "Medichamite",
    "Meganiumite",
    "Mental Herb",
    "Meowsticite",
    "Metal Coat",
    "Miracle Seed",
    "Mystic Water",
    "Never-Melt Ice",
    "Occa Berry",
    "Oran Berry",
    "Passho Berry",
    "Payapa Berry",
    "Pecha Berry",
    "Persim Berry",
    "Pidgeotite",
    "Pinsirite",
    "Poison Barb",
    "Quick Claw",
    "Rawst Berry",
    "Rindo Berry",
    "Roseli Berry",
    "Sablenite",
    "Scizorite",
    "Scope Lens",
    "Scovillainite",
    "Sharp Beak",
    "Sharpedonite",
    "Shell Bell",
    "Shuca Berry",
    "Silk Scarf",
    "SilverPowder",
    "Sitrus Berry",
    "Skarmorite",
    "Slowbronite",
    "Soft Sand",
    "Spell Tag",
    "Starminite",
    "Steelixite",
    "Tanga Berry",
    "TwistedSpoon",
    "Tyranitarite",
    "Venusaurite",
    "Victreebelite",
    "Wacan Berry",
    "White Herb",
    "Yache Berry",
];
