//! Allow-list of legal moves for Pokémon Champions Regulation M-A.
//!
//! Source: <https://metavgc.com/guides/pokemon-champions-format-legal-pokemon-items-moves>
//! (snapshot extracted from the Next.js flight payload, 467 entries).
//!
//! Comparisons go through [`super::common::canonical`] so spacing /
//! punctuation differences (`U-turn`, `Will-O-Wisp`, `Mud-Slap`) collapse to
//! the same key as the canonicalised user input.

pub const ALLOWED_MOVES_MA: &[&str] = &[
    "Acid Armor",
    "Acid Spray",
    "Acrobatics",
    "Acupressure",
    "Aerial Ace",
    "After You",
    "Agility",
    "Air Cutter",
    "Air Slash",
    "Alluring Voice",
    "Ally Switch",
    "Amnesia",
    "Ancient Power",
    "Apple Acid",
    "Aqua Cutter",
    "Aqua Ring",
    "Aqua Step",
    "Armor Cannon",
    "Aromatic Mist",
    "Assurance",
    "Attract",
    "Aura Sphere",
    "Aura Wheel",
    "Aurora Veil",
    "Avalanche",
    "Axe Kick",
    "Baby-Doll Eyes",
    "Baneful Bunker",
    "Baton Pass",
    "Beak Blast",
    "Beat Up",
    "Belch",
    "Belly Drum",
    "Bind",
    "Bite",
    "Bitter Blade",
    "Bitter Malice",
    "Blast Burn",
    "Blaze Kick",
    "Blizzard",
    "Block",
    "Body Press",
    "Body Slam",
    "Bone Rush",
    "Bounce",
    "Brave Bird",
    "Breaking Swipe",
    "Brick Break",
    "Bug Bite",
    "Bug Buzz",
    "Bulk Up",
    "Bulldoze",
    "Bullet Seed",
    "Burn Up",
    "Burning Jealousy",
    "Calm Mind",
    "Ceaseless Edge",
    "Charge",
    "Charge Beam",
    "Charm",
    "Chilling Water",
    "Chilly Reception",
    "Circle Throw",
    "Clanging Scales",
    "Clangorous Soul",
    "Clear Smog",
    "Close Combat",
    "Coaching",
    "Coil",
    "Comeuppance",
    "Confuse Ray",
    "Copycat",
    "Corrosive Gas",
    "Cosmic Power",
    "Cotton Guard",
    "Cotton Spore",
    "Counter",
    "Covet",
    "Crabhammer",
    "Cross Chop",
    "Cross Poison",
    "Crunch",
    "Crush Claw",
    "Dark Pulse",
    "Darkest Lariat",
    "Decorate",
    "Defog",
    "Destiny Bond",
    "Detect",
    "Dig",
    "Dire Claw",
    "Disable",
    "Discharge",
    "Dive",
    "Double Hit",
    "Double Shock",
    "Double Team",
    "Double-Edge",
    "Draco Meteor",
    "Dragon Cheer",
    "Dragon Dance",
    "Dragon Darts",
    "Dragon Rush",
    "Dragon Tail",
    "Drain Punch",
    "Draining Kiss",
    "Drill Run",
    "Dual Wingbeat",
    "Dynamic Punch",
    "Earth Power",
    "Earthquake",
    "Eerie Impulse",
    "Eerie Spell",
    "Electric Terrain",
    "Electrify",
    "Electro Ball",
    "Electro Shot",
    "Electroweb",
    "Encore",
    "Endeavor",
    "Endure",
    "Energy Ball",
    "Entrainment",
    "Eruption",
    "Expanding Force",
    "Explosion",
    "Extrasensory",
    "Facade",
    "Fairy Lock",
    "Fake Out",
    "Fake Tears",
    "Feather Dance",
    "Feint",
    "Fell Stinger",
    "Fickle Beam",
    "Fiery Dance",
    "Final Gambit",
    "Fire Blast",
    "Fire Fang",
    "Fire Lash",
    "Fire Punch",
    "Fire Spin",
    "First Impression",
    "Fissure",
    "Flail",
    "Flame Charge",
    "Flamethrower",
    "Flare Blitz",
    "Flash Cannon",
    "Flatter",
    "Fling",
    "Flip Turn",
    "Flower Trick",
    "Fly",
    "Flying Press",
    "Focus Blast",
    "Focus Energy",
    "Focus Punch",
    "Follow Me",
    "Forest's Curse",
    "Foul Play",
    "Freeze-Dry",
    "Frenzy Plant",
    "Frost Breath",
    "Future Sight",
    "Gastro Acid",
    "Giga Drain",
    "Giga Impact",
    "Gigaton Hammer",
    "Glare",
    "Grass Knot",
    "Grassy Glide",
    "Grassy Terrain",
    "Grav Apple",
    "Gravity",
    "Growth",
    "Guard Split",
    "Guard Swap",
    "Guillotine",
    "Gunk Shot",
    "Gyro Ball",
    "Hammer Arm",
    "Hard Press",
    "Haze",
    "Head Smash",
    "Headlong Rush",
    "Heal Bell",
    "Heal Pulse",
    "Healing Wish",
    "Heat Crash",
    "Heat Wave",
    "Heavy Slam",
    "Helping Hand",
    "Hex",
    "High Jump Kick",
    "Horn Drill",
    "Horn Leech",
    "Howl",
    "Hurricane",
    "Hydro Cannon",
    "Hyper Beam",
    "Hypnosis",
    "Ice Beam",
    "Ice Fang",
    "Ice Hammer",
    "Ice Punch",
    "Ice Spinner",
    "Icicle Crash",
    "Icicle Spear",
    "Icy Wind",
    "Imprison",
    "Infernal Parade",
    "Inferno",
    "Infestation",
    "Ingrain",
    "Instruct",
    "Iron Defense",
    "Iron Head",
    "Iron Tail",
    "King's Shield",
    "Knock Off",
    "Kowtow Cleave",
    "Lash Out",
    "Last Resort",
    "Last Respects",
    "Lava Plume",
    "Leaf Blade",
    "Leaf Storm",
    "Leech Life",
    "Leech Seed",
    "Life Dew",
    "Light of Ruin",
    "Light Screen",
    "Liquidation",
    "Lock-On",
    "Low Kick",
    "Low Sweep",
    "Lumina Crash",
    "Lunge",
    "Magic Powder",
    "Magic Room",
    "Magnet Rise",
    "Magnetic Flux",
    "Matcha Gotcha",
    "Mean Look",
    "Memento",
    "Metal Burst",
    "Metal Sound",
    "Meteor Beam",
    "Meteor Mash",
    "Milk Drink",
    "Minimize",
    "Mirror Coat",
    "Misty Explosion",
    "Misty Terrain",
    "Moonblast",
    "Moonlight",
    "Morning Sun",
    "Mortal Spin",
    "Mountain Gale",
    "Mud Shot",
    "Mud-Slap",
    "Muddy Water",
    "Mystical Fire",
    "Nasty Plot",
    "Night Daze",
    "Night Shade",
    "Night Slash",
    "Noble Roar",
    "Nuzzle",
    "Outrage",
    "Overheat",
    "Pain Split",
    "Parabolic Charge",
    "Parting Shot",
    "Payback",
    "Perish Song",
    "Petal Dance",
    "Phantom Force",
    "Pin Missile",
    "Play Rough",
    "Pluck",
    "Poison Fang",
    "Poison Jab",
    "Poison Powder",
    "Pollen Puff",
    "Poltergeist",
    "Population Bomb",
    "Pounce",
    "Power Shift",
    "Power Split",
    "Power Swap",
    "Power Trick",
    "Power Trip",
    "Protect",
    "Psych Up",
    "Psychic",
    "Psychic Fangs",
    "Psychic Noise",
    "Psychic Terrain",
    "Psycho Cut",
    "Psyshield Bash",
    "Psyshock",
    "Quash",
    "Quick Guard",
    "Quiver Dance",
    "Rage Powder",
    "Raging Bull",
    "Raging Fury",
    "Rain Dance",
    "Rapid Spin",
    "Razor Shell",
    "Recover",
    "Recycle",
    "Reflect",
    "Reflect Type",
    "Rest",
    "Reversal",
    "Revival Blessing",
    "Rising Voltage",
    "Roar",
    "Rock Blast",
    "Rock Polish",
    "Rock Slide",
    "Rock Tomb",
    "Rock Wrecker",
    "Role Play",
    "Roost",
    "Round",
    "Sacred Sword",
    "Safeguard",
    "Salt Cure",
    "Sand Tomb",
    "Sandstorm",
    "Scald",
    "Scale Shot",
    "Scary Face",
    "Scorching Sands",
    "Screech",
    "Seismic Toss",
    "Self-Destruct",
    "Shadow Ball",
    "Shadow Claw",
    "Shadow Punch",
    "Shed Tail",
    "Sheer Cold",
    "Shell Side Arm",
    "Shell Smash",
    "Shelter",
    "Simple Beam",
    "Sing",
    "Skill Swap",
    "Skitter Smack",
    "Sky Attack",
    "Slack Off",
    "Sleep Powder",
    "Sleep Talk",
    "Sludge Bomb",
    "Sludge Wave",
    "Smack Down",
    "Smart Strike",
    "Snap Trap",
    "Snarl",
    "Snore",
    "Snowscape",
    "Soak",
    "Soft-Boiled",
    "Solar Beam",
    "Solar Blade",
    "Sparkling Aria",
    "Speed Swap",
    "Spicy Extract",
    "Spikes",
    "Spiky Shield",
    "Spirit Shackle",
    "Spit Up",
    "Spite",
    "Spore",
    "Stealth Rock",
    "Steel Beam",
    "Steel Roller",
    "Steel Wing",
    "Sticky Web",
    "Stockpile",
    "Stomping Tantrum",
    "Stone Axe",
    "Stone Edge",
    "Stored Power",
    "Storm Throw",
    "Strength Sap",
    "String Shot",
    "Struggle Bug",
    "Stuff Cheeks",
    "Stun Spore",
    "Substitute",
    "Sucker Punch",
    "Sunny Day",
    "Super Fang",
    "Supercell Slam",
    "Superpower",
    "Surf",
    "Swagger",
    "Swallow",
    "Sweet Kiss",
    "Sweet Scent",
    "Switcheroo",
    "Swords Dance",
    "Synthesis",
    "Syrup Bomb",
    "Tail Slap",
    "Tailwind",
    "Taunt",
    "Tearful Look",
    "Teatime",
    "Teeter Dance",
    "Temper Flare",
    "Terrain Pulse",
    "Thief",
    "Thrash",
    "Throat Chop",
    "Thunder",
    "Thunder Fang",
    "Thunder Punch",
    "Thunder Wave",
    "Thunderbolt",
    "Tickle",
    "Tidy Up",
    "Torch Song",
    "Torment",
    "Toxic",
    "Toxic Spikes",
    "Toxic Thread",
    "Trailblaze",
    "Transform",
    "Tri Attack",
    "Trick",
    "Trick Room",
    "Trick-or-Treat",
    "Triple Arrows",
    "Triple Axel",
    "Trop Kick",
    "Twin Beam",
    "U-turn",
    "Upper Hand",
    "Uproar",
    "Venoshock",
    "Volt Switch",
    "Volt Tackle",
    "Water Pulse",
    "Water Shuriken",
    "Water Spout",
    "Waterfall",
    "Wave Crash",
    "Weather Ball",
    "Whirlpool",
    "Whirlwind",
    "Wide Guard",
    "Wild Charge",
    "Will-O-Wisp",
    "Wish",
    "Wonder Room",
    "Wood Hammer",
    "Worry Seed",
    "Wrap",
    "Yawn",
    "Zap Cannon",
    "Zen Headbutt",
];
