//! Species that Regulation M-B adds on top of Regulation M-A.
//!
//! M-B is a superset of M-A (every M-A species stays legal), so this file only
//! holds the **delta**: 22 new base species + 75 Mega Evolution forms = 97
//! entries. `RegMbRules` unions this with `ALLOWED_SPECIES_MA` at build time.
//!
//! Mega rule (official in-game text): a Mega is legal iff its base species is in
//! the M-B roster. The two banned `-Mega-Z` forms (Lucario, Garchomp) are
//! omitted. Sources cross-checked: Bulbapedia (Regulation Set M-B, explicit
//! 75-mega list), victoryroad.pro, game8, Serebii roster, pokebase.app. The
//! 75-mega set was validated two independent ways (roster-membership derivation
//! ≡ Bulbapedia's enumerated list, zero diff).
//!
//! Names use Showdown form naming (`Charizard-Mega-X`, `Raichu-Mega-Y`) and are
//! compared through [`super::common::canonical`], which strips dashes/spaces so
//! `Charizard-Mega-X` → `charizardmegax` — distinct from M-A's `charizard`.

pub const ALLOWED_SPECIES_MB_NEW: &[&str] = &[
    // --- 22 new base species (vs M-A) ---
    "Annihilape",
    "Barbaracle",
    "Blaziken",
    "Dragalge",
    "Eelektross",
    "Falinks",
    "Gholdengo",
    "Grimmsnarl",
    "Houndstone",
    "Malamar",
    "Mawile",
    "Metagross",
    "Musharna",
    "Overqwil",
    "Pyroar",
    "Qwilfish",
    "Sceptile",
    "Scolipede",
    "Scrafty",
    "Staraptor",
    "Swampert",
    "Vileplume",
    // --- 75 Mega forms (Showdown naming) ---
    "Abomasnow-Mega",
    "Absol-Mega",
    "Aerodactyl-Mega",
    "Aggron-Mega",
    "Alakazam-Mega",
    "Altaria-Mega",
    "Ampharos-Mega",
    "Audino-Mega",
    "Banette-Mega",
    "Barbaracle-Mega",
    "Beedrill-Mega",
    "Blastoise-Mega",
    "Blaziken-Mega",
    "Camerupt-Mega",
    "Chandelure-Mega",
    "Charizard-Mega-X",
    "Charizard-Mega-Y",
    "Chesnaught-Mega",
    "Chimecho-Mega",
    "Clefable-Mega",
    "Crabominable-Mega",
    "Delphox-Mega",
    "Dragalge-Mega",
    "Dragonite-Mega",
    "Drampa-Mega",
    "Eelektross-Mega",
    "Emboar-Mega",
    "Excadrill-Mega",
    "Falinks-Mega",
    "Feraligatr-Mega",
    "Floette-Mega",
    "Froslass-Mega",
    "Gallade-Mega",
    "Garchomp-Mega",
    "Gardevoir-Mega",
    "Gengar-Mega",
    "Glalie-Mega",
    "Glimmora-Mega",
    "Golurk-Mega",
    "Greninja-Mega",
    "Gyarados-Mega",
    "Hawlucha-Mega",
    "Heracross-Mega",
    "Houndoom-Mega",
    "Kangaskhan-Mega",
    "Lopunny-Mega",
    "Lucario-Mega",
    "Malamar-Mega",
    "Manectric-Mega",
    "Mawile-Mega",
    "Medicham-Mega",
    "Meganium-Mega",
    "Meowstic-Mega",
    "Metagross-Mega",
    "Pidgeot-Mega",
    "Pinsir-Mega",
    "Pyroar-Mega",
    "Raichu-Mega-X",
    "Raichu-Mega-Y",
    "Sableye-Mega",
    "Sceptile-Mega",
    "Scizor-Mega",
    "Scolipede-Mega",
    "Scovillain-Mega",
    "Scrafty-Mega",
    "Sharpedo-Mega",
    "Skarmory-Mega",
    "Slowbro-Mega",
    "Staraptor-Mega",
    "Starmie-Mega",
    "Steelix-Mega",
    "Swampert-Mega",
    "Tyranitar-Mega",
    "Venusaur-Mega",
    "Victreebel-Mega",
];
