// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Ability = { id: string, name: string, description: string, };

export type ChampionsReport = { tournaments: Array<ChampionsTournament>, fetched_at: string, };

export type ChampionsTournament = { id: string, name: string, date: string | null, players: number | null, format: string | null, organizer_id: string | null, };

export type DecklistPokemon = { id: string | null, name: string, item: string | null, ability: string | null, tera_type: string | null, moves: Array<string>, sprite_url: string, sprite_fallback_url: string | null, };

export type EvSpread = { hp: number, atk: number, def: number, spa: number, spd: number, spe: number, };

/**
 * Competitive format. Multi-variant: frontend can switch freely.
 */
export type Format = "regulation-m-a" | "champions-singles" | "regulation-i" | "gen9-ou";

export type Item = { id: string, name: string, description: string, };

export type LocalizedName = { en: string, es: string, };

export type MetaSnapshot = { format: Format, generated_at: string, source: string, tournaments_used: number, total_entries: number, pokemon: Array<PokemonUsage>, top_items: Array<UsageEntry>, top_moves: Array<UsageEntry>, top_abilities: Array<UsageEntry>, top_tera: Array<UsageEntry>, };

export type Move = { id: string, name: string, type_: PokemonType, category: MoveCategory, base_power: number, accuracy: number, pp: number, description: string, };

export type MoveCategory = "Physical" | "Special" | "Status";

export type MoveSummary = { id: string, name: string, type_: PokemonType, category: MoveCategory, };

export type MoveUsage = { name: string, usage_percent: number, };

export type Nature = "Hardy" | "Lonely" | "Brave" | "Adamant" | "Naughty" | "Bold" | "Docile" | "Relaxed" | "Impish" | "Lax" | "Timid" | "Hasty" | "Serious" | "Jolly" | "Naive" | "Modest" | "Mild" | "Quiet" | "Bashful" | "Rash" | "Calm" | "Gentle" | "Sassy" | "Careful" | "Quirky";

export type Pokemon = { 
/**
 * Showdown canonical id (e.g. "incineroar").
 */
id: string, 
/**
 * Display name (e.g. "Incineroar").
 */
name: string, 
/**
 * National Pokédex number. 0 for entries that have no number (cosmetic forms).
 */
num: number, types: Array<PokemonType>, base_stats: Stats, abilities: Array<string>, sprite_url: string, 
/**
 * Secondary sprite URL tried by the frontend when `sprite_url` 404s.
 * Variant-aware: indexed by slug, not dex number.
 */
sprite_fallback_url: string | null, };

/**
 * A single competitive set (item, ability, nature, EVs, moves).
 * Sourced from `data.pkmn.cc`. Fields are tolerant — items/abilities can be
 * missing for ability-locked or item-less sets.
 */
export type PokemonSet = { name: string, item: string | null, ability: string | null, nature: string | null, 
/**
 * Tera type(s) recommended for this set. May be empty.
 */
tera_types: Array<string>, evs: EvSpread, 
/**
 * Move list. Each slot is at most one move; alternative options are
 * joined with " / " for display (e.g. `"Air Slash / Dragon Pulse"`).
 */
moves: Array<string>, };

export type PokemonType = "Normal" | "Fire" | "Water" | "Electric" | "Grass" | "Ice" | "Fighting" | "Poison" | "Ground" | "Flying" | "Psychic" | "Bug" | "Rock" | "Ghost" | "Dragon" | "Dark" | "Steel" | "Fairy" | "Stellar";

export type PokemonUsage = { species: string, usage_percent: number, count: number, top_items: Array<UsageEntry>, top_moves: Array<UsageEntry>, top_abilities: Array<UsageEntry>, top_tera: Array<UsageEntry>, top_teammates: Array<UsageEntry>, sprite_url: string, };

/**
 * Bundle of curated sets for a Pokémon, split by play style.
 * `*_source` carries the slug actually used after the fallback chain (so the
 * UI can disclose where the data came from).
 */
export type SetsBundle = { species: string, doubles: Array<PokemonSet>, singles: Array<PokemonSet>, doubles_source: string | null, singles_source: string | null, };

export type Stats = { hp: number, atk: number, def: number, spa: number, spd: number, spe: number, };

export type Team = { id: number | null, name: string, format: Format, notes: string | null, members: Array<TeamMember>, created_at: string | null, updated_at: string | null, };

export type TeamMember = { species: string, item: string | null, ability: string | null, nature: Nature | null, tera_type: PokemonType | null, moves: Array<string>, evs: EvSpread, };

export type TeamValidationError = { "WrongSize": number } | { "InvalidEvs": number } | { "InvalidMoves": number } | { "EmptySpecies": number } | "EmptyName";

/**
 * Tera Type uses the same type list as Pokémon (including Stellar).
 * We alias to keep the domain small.
 */
export type TeraType = PokemonType;

export type TeraUsage = { tera_type: string, usage_percent: number, };

export type TopTeam = { tournament: string, placing: number | null, player: string | null, record: string | null, members: Array<TopTeamMember>, };

export type TopTeamMember = { species: string, sprite_url: string, item: string | null, tera_type: string | null, };

export type TournamentStanding = { placing: number | null, player_name: string | null, player_id: string | null, country: string | null, record: string | null, wins: number, losses: number, ties: number, decklist: Array<DecklistPokemon>, };

export type TranslationTable = { abilities: { [key in string]?: LocalizedName }, moves: { [key in string]?: LocalizedName }, items: { [key in string]?: LocalizedName }, };

export type UsageEntry = { name: string, usage_percent: number, count: number, };

export type Violation = { "kind": "team_incomplete", filled: number, } | { "kind": "species_not_allowed", species: string, } | { "kind": "item_banned", species: string, item: string, } | { "kind": "move_banned", species: string, mv: string, } | { "kind": "too_many_restricted", allowed: number, found: number, } | { "kind": "restricted_not_in_season", species: string, season: string, } | { "kind": "duplicate_species", species: string, } | { "kind": "duplicate_item", item: string, };
