/**
 * Facade over ts-rs generated types.
 *
 * `types.generated.ts` is the source of truth (regenerated by
 * `cargo test` in src-tauri). This file re-exports everything from there and
 * adds frontend-only helpers/constants that don't exist on the Rust side.
 */

export type {
  Ability,
  ChampionsReport,
  ChampionsTournament,
  DecklistPokemon,
  EntityDescriptions,
  EvSpread,
  Format,
  Item,
  LocalizedName,
  MetaSnapshot,
  Move,
  MoveCategory,
  MoveSummary,
  MoveUsage,
  MovesetUsage,
  Nature,
  Pokemon,
  PokemonSet,
  PokemonType,
  PokemonUsage,
  SetsBundle,
  Stats,
  Team,
  TeamMember,
  TeamValidationError,
  TeraType,
  TeraUsage,
  TopTeam,
  TopTeamMember,
  TopTeamsMeta,
  TopTeamsReport,
  TournamentStanding,
  TranslationTable,
  UpcomingTournament,
  UsageEntry,
  Violation,
} from "./types.generated";

import type { Format, Nature, PokemonType, Team, TeamMember } from "./types.generated";

export interface FormatOption {
  value: Format;
  label: string;
  /** Readonly in the UI; selection is blocked. Season hasn't started yet. */
  disabled?: boolean;
  /** Optional i18n key for a "coming soon" style badge shown beside the label. */
  badgeKey?: string;
}

export const ALL_FORMATS: FormatOption[] = [
  { value: "regulation-m-a", label: "Regulation M-A (M-1)" },
  {
    value: "regulation-m-a",
    label: "Regulation M-A (M-2)",
    disabled: true,
    badgeKey: "regulations.coming_soon",
  },
];

/**
 * Mythical species that cannot be picked in VGC Regulation M-A. This mirrors
 * the backend list in `services/regulations/reg_ma.rs`; keep them in sync.
 * Stored as lowercase alphanumeric ids so we can compare against canonicalised
 * species names (handles Deoxys forms, Shaymin-Sky, etc.).
 */
export const BANNED_SPECIES_MA: ReadonlySet<string> = new Set([
  "mew",
  "celebi",
  "jirachi",
  "deoxys",
  "phione",
  "manaphy",
  "darkrai",
  "shaymin",
  "arceus",
  "victini",
  "keldeo",
  "meloetta",
  "genesect",
  "diancie",
  "hoopa",
  "volcanion",
  "magearna",
  "marshadow",
  "zeraora",
  "zarude",
  "pecharunt",
]);

export function canonicalSpeciesId(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "");
}

export function isBannedInFormat(species: string, format: Format): boolean {
  if (format !== "regulation-m-a") return false;
  const id = canonicalSpeciesId(species);
  if (BANNED_SPECIES_MA.has(id)) return true;
  // Strip "-Shadow", "-Sky" style form suffixes so Shaymin-Sky also matches.
  const base = species.split("-")[0];
  if (base && BANNED_SPECIES_MA.has(canonicalSpeciesId(base))) return true;
  return false;
}

export const ALL_TYPES: PokemonType[] = [
  "Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting",
  "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost",
  "Dragon", "Dark", "Steel", "Fairy", "Stellar",
];

export const ALL_NATURES: Nature[] = [
  "Hardy","Lonely","Brave","Adamant","Naughty","Bold","Docile","Relaxed",
  "Impish","Lax","Timid","Hasty","Serious","Jolly","Naive","Modest","Mild",
  "Quiet","Bashful","Rash","Calm","Gentle","Sassy","Careful","Quirky",
];

export function generationOf(num: number): number {
  if (num >= 1 && num <= 151) return 1;
  if (num <= 251) return 2;
  if (num <= 386) return 3;
  if (num <= 493) return 4;
  if (num <= 649) return 5;
  if (num <= 721) return 6;
  if (num <= 809) return 7;
  if (num <= 905) return 8;
  if (num <= 1025) return 9;
  return 0;
}

export function emptyTeamMember(species = ""): TeamMember {
  return {
    species,
    item: null,
    ability: null,
    nature: null,
    tera_type: null,
    moves: [],
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
  };
}

export function emptyTeam(format: Format = "regulation-m-a"): Team {
  return {
    id: null,
    name: "",
    format,
    notes: null,
    members: Array.from({ length: 6 }, () => emptyTeamMember()),
    created_at: null,
    updated_at: null,
  };
}
