/**
 * Facade over ts-rs generated types.
 *
 * `types.generated.ts` is the source of truth (regenerated by
 * `cargo test` in src-tauri). This file re-exports everything from there and
 * adds frontend-only helpers/constants that don't exist on the Rust side.
 */

export type {
  Ability,
  ChampionsReport,
  ChampionsTournament,
  DecklistPokemon,
  EvSpread,
  Format,
  Item,
  MetaSnapshot,
  Move,
  MoveCategory,
  MoveSummary,
  MoveUsage,
  Nature,
  Pokemon,
  PokemonSet,
  PokemonType,
  PokemonUsage,
  SetsBundle,
  Stats,
  Team,
  TeamMember,
  TeamValidationError,
  TeraType,
  TeraUsage,
  TopTeam,
  TopTeamMember,
  TournamentStanding,
  UsageEntry,
  Violation,
} from "./types.generated";

import type { Format, Nature, PokemonType, Team, TeamMember } from "./types.generated";

export const ALL_FORMATS: { value: Format; label: string }[] = [
  { value: "regulation-m-a", label: "Regulation M-A (Champions doubles)" },
  { value: "champions-singles", label: "Champions Singles" },
  { value: "regulation-i", label: "Regulation I (doubles, active)" },
  { value: "gen9-ou", label: "Gen 9 OU (singles)" },
];

export const ALL_TYPES: PokemonType[] = [
  "Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting",
  "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost",
  "Dragon", "Dark", "Steel", "Fairy", "Stellar",
];

export const ALL_NATURES: Nature[] = [
  "Hardy","Lonely","Brave","Adamant","Naughty","Bold","Docile","Relaxed",
  "Impish","Lax","Timid","Hasty","Serious","Jolly","Naive","Modest","Mild",
  "Quiet","Bashful","Rash","Calm","Gentle","Sassy","Careful","Quirky",
];

export function generationOf(num: number): number {
  if (num >= 1 && num <= 151) return 1;
  if (num <= 251) return 2;
  if (num <= 386) return 3;
  if (num <= 493) return 4;
  if (num <= 649) return 5;
  if (num <= 721) return 6;
  if (num <= 809) return 7;
  if (num <= 905) return 8;
  if (num <= 1025) return 9;
  return 0;
}

export function emptyTeamMember(species = ""): TeamMember {
  return {
    species,
    item: null,
    ability: null,
    nature: null,
    tera_type: null,
    moves: [],
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
  };
}

export function emptyTeam(format: Format = "regulation-m-a"): Team {
  return {
    id: null,
    name: "",
    format,
    notes: null,
    members: Array.from({ length: 6 }, () => emptyTeamMember()),
    created_at: null,
    updated_at: null,
  };
}
