/**
 * Facade over ts-rs generated types.
 *
 * `types.generated.ts` is the source of truth (regenerated by
 * `cargo test` in src-tauri). This file re-exports everything from there and
 * adds frontend-only helpers/constants that don't exist on the Rust side.
 */

export type {
  Ability,
  ChampionsReport,
  ChampionsSearchHit,
  ChampionsTournament,
  DecklistPokemon,
  EntityDescriptions,
  SearchHitKind,
  EvSpread,
  Format,
  Item,
  LocalizedDescription,
  LocalizedName,
  MetaSnapshot,
  Move,
  MoveCategory,
  MoveSummary,
  MoveUsage,
  MovesetUsage,
  Nature,
  PikalyticsEntry,
  PikalyticsEvSpread,
  PikalyticsItem,
  PikalyticsTeammate,
  Pokemon,
  PokemonSet,
  PokemonType,
  PokemonUsage,
  SetsBundle,
  Stats,
  Team,
  TeamMember,
  TeamValidationError,
  TeraType,
  TeraUsage,
  TeammateUsage,
  TopTeam,
  TopTeamMember,
  TopTeamsMeta,
  TopTeamsReport,
  TournamentStanding,
  TranslationTable,
  TrendingPokemon,
  TrendingReport,
  UpcomingTournament,
  UpdateInfo,
  UsageEntry,
  Violation,
  EvStatSpread,
} from "./types.generated";

import type { Format, Nature, PokemonType, Team, TeamMember } from "./types.generated";

export interface FormatOption {
  value: Format;
  label: string;
  /** Readonly in the UI; selection is blocked. Season hasn't started yet. */
  disabled?: boolean;
  /** Optional i18n key for a "coming soon" style badge shown beside the label. */
  badgeKey?: string;
  /** Optional i18n key for a tooltip shown when the option is disabled
   *  (e.g. start date of the upcoming season). Supports interpolation. */
  disabledTooltipKey?: string;
  /** Optional interpolation params for `disabledTooltipKey`. */
  disabledTooltipParams?: Record<string, string>;
}

export const ALL_FORMATS: FormatOption[] = [
  { value: "regulation-m-b", label: "Regulation M-B (M-3)" },
  { value: "regulation-m-a", label: "Regulation M-A (M-2)" },
];

/**
 * Canonical key for comparing display names against backend allow-lists.
 * Mirrors `regulations::common::canonical` on the Rust side: lowercase,
 * ascii-alphanumeric only. Lets `"Choice Scarf"`, `"choice-scarf"`, and
 * `"CHOICESCARF"` collide, and `Mr Rime` / `Mr. Rime` agree.
 */
export function canonicalSpeciesId(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/**
 * Form suffixes that represent gameplay mechanics no current VGC
 * regulation permits (Mega Evolution, Gigantamax, Primal Reversion,
 * Eternamax). Mirrors the backend constant in
 * `services/regulations/common.rs` so the picker hides what the
 * validator would reject.
 */
const FORBIDDEN_FORM_TOKENS: ReadonlySet<string> = new Set([
  "mega",
  "megax",
  "megay",
  "primal",
  "gmax",
  "eternamax",
]);

function hasForbiddenFormToken(name: string): boolean {
  const tail = name.split("-").slice(1).map((s) => s.toLowerCase());
  if (tail.length === 0) return false;
  if (FORBIDDEN_FORM_TOKENS.has(tail.join(""))) return true;
  return tail.some((seg) => FORBIDDEN_FORM_TOKENS.has(seg));
}

/**
 * `true` when `name` matches an entry in `allowedKeys` either directly or
 * via its base form (Showdown form suffix stripped: `Slowking-Galar` →
 * `Slowking`). `allowedKeys` must already contain canonicalised entries.
 *
 * Mega/Gmax/Primal/Eternamax forms never fall back to base — they require
 * an explicit allow-list entry, which no current regulation provides.
 */
export function isAllowedName(name: string, allowedKeys: ReadonlySet<string>): boolean {
  if (allowedKeys.size === 0) return true;
  if (allowedKeys.has(canonicalSpeciesId(name))) return true;
  if (hasForbiddenFormToken(name)) return false;
  const base = name.split("-")[0];
  if (base && allowedKeys.has(canonicalSpeciesId(base))) return true;
  return false;
}

export const ALL_TYPES: PokemonType[] = [
  "Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting",
  "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost",
  "Dragon", "Dark", "Steel", "Fairy", "Stellar",
];

export const ALL_NATURES: Nature[] = [
  "Hardy","Lonely","Brave","Adamant","Naughty","Bold","Docile","Relaxed",
  "Impish","Lax","Timid","Hasty","Serious","Jolly","Naive","Modest","Mild",
  "Quiet","Bashful","Rash","Calm","Gentle","Sassy","Careful","Quirky",
];

export function generationOf(num: number): number {
  if (num >= 1 && num <= 151) return 1;
  if (num <= 251) return 2;
  if (num <= 386) return 3;
  if (num <= 493) return 4;
  if (num <= 649) return 5;
  if (num <= 721) return 6;
  if (num <= 809) return 7;
  if (num <= 905) return 8;
  if (num <= 1025) return 9;
  return 0;
}

export function emptyTeamMember(species = ""): TeamMember {
  return {
    species,
    item: null,
    ability: null,
    nature: null,
    tera_type: null,
    moves: [],
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    level: 50,
    gender: null,
    shiny: false,
    nickname: null,
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
  };
}

export function emptyTeam(format: Format = "regulation-m-b"): Team {
  return {
    id: null,
    name: "",
    format,
    notes: null,
    members: Array.from({ length: 6 }, () => emptyTeamMember()),
    created_at: null,
    updated_at: null,
  };
}
